---
- name: install python dev on 16.04
  become: True
  become_user: root
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - python3
    - python3-pip
    - python3-dev
    - python3-venv
  when: ansible_distribution_version == '16.04'


- name: install python dev on 14.04
  become: True
  become_user: root
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - python3
    - python3-pip
    - python3-dev
    - python3.4-venv
  when: ansible_distribution_version == '14.04'
