---
- name: install supervisord
  apt: name=supervisor state=present

- name: set permissions on supervisor config and log directories
  file: path={{ item }} group={{ app_group }} state=directory mode=0755
  with_items:
     - /etc/supervisor
     - /etc/supervisor/conf.d
     - /var/log/supervisor

- name: modify supervisor configuration
  ini_file: dest=/etc/supervisor/supervisord.conf section=unix_http_server
            option={{ item.key }} value={{ item.value }}
  with_dict:
      chmod: "0770"
      chown: root:{{ app_group }}

- name: upload supervisor app configuration to web server
  template: src=supervisor/app_supervisor.conf dest=/etc/supervisor/conf.d/{{ supervisor_app_config }}
  notify: restart supervisor
